#!/bin/bash
rm ./._.DS_Store
rm ./._build.xml
rm ./._FXTalk.keystore
rm ./._lib
rm ./._LICENSE
rm ./._manifest.mf
rm ./._nbproject
rm ./._package
rm ./._README.txt
rm ./._src
rm ./lib/._.DS_Store
rm ./lib/._ant-contrib-1.0.jar
rm ./lib/._ant-javafx.jar
rm ./lib/._commons-io-2.4.jar
rm ./lib/._commons-logging-1.1.1.jar
rm ./lib/._CopyLibs
rm ./lib/._nblibraries.properties
rm ./lib/._ScenicView.jar
rm ./lib/._smack.jar
rm ./lib/._smackx-debug.jar
rm ./lib/._smackx-jingle.jar
rm ./lib/._smackx.jar
rm ./lib/CopyLibs/._org-netbeans-modules-java-j2seproject-copylibstask.jar
rm ./nbproject/._build-impl.xml
rm ./nbproject/._configs
rm ./nbproject/._genfiles.properties
rm ./nbproject/._jfx-impl.xml
rm ./nbproject/._jfx-impl_backup.xml
rm ./nbproject/._jfx-impl_backup_1.xml
rm ./nbproject/._jfx-impl_backup_2.xml
rm ./nbproject/._jfx-impl_backup_3.xml
rm ./nbproject/._private
rm ./nbproject/._project.properties
rm ./nbproject/._project.xml
rm ./nbproject/._UPDATED.TXT
rm ./nbproject/configs/._Run_as_WebStart.properties
rm ./nbproject/configs/._Run_in_Browser.properties
rm ./nbproject/private/._configs
rm ./nbproject/private/._private.properties
rm ./nbproject/private/._private.xml
rm ./nbproject/private/configs/._Run_as_WebStart.properties
rm ./nbproject/private/configs/._Run_in_Browser.properties
rm ./package/._.DS_Store
rm ./package/._linux
rm ./package/._macosx
rm ./package/._windows
rm ./package/linux/._.DS_Store
rm ./package/linux/._FXTalk.png
rm ./package/macosx/._.DS_Store
rm ./package/macosx/._FXTalk copy.icns
rm ./package/macosx/._FXTalk-background.png
rm ./package/macosx/._FXTalk-dmg-setup.scpt
rm ./package/macosx/._FXTalk-post-image.sh
rm ./package/macosx/._FXTalk-post-image.shpwd
rm ./package/macosx/._FXTalk-volume-original.icns
rm ./package/macosx/._Info.plist
rm ./package/windows/._bundle.wxi
rm ./package/windows/._FXTalk-post-image.wsf
rm ./package/windows/._FXTalk-setup-icon.bmp
rm ./package/windows/._FXTalk.ico
rm ./package/windows/._FXTalk.iss
rm ./package/windows/._FXTalk.png
rm ./package/windows/._FXTalk.wxs
rm ./src/._.DS_Store
rm ./src/._fxtalk
rm ./src/fxtalk/._.DS_Store
rm ./src/fxtalk/._assets
rm ./src/fxtalk/._beans
rm ./src/fxtalk/._FXTalkApp.java
rm ./src/fxtalk/._network
rm ./src/fxtalk/._trackers
rm ./src/fxtalk/._ui
rm ./src/fxtalk/._utils
